name: Go CI
on:
  push:
  pull_request:
    branches:
        - main
        - dev 
permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from github
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v4
        with:
            go-version-file: go.mod
      - name: download the package
        run: go mod download
      - name: verify dependencies
        run: go mod tidy && git diff --exit-code
      - name: check formatting
        run: test -z "$(gofmt -l .)"
      - name: build project
        run: go build ./...
      - name: go vet
        run: go vet ./...
      - name: Run tests
        run: go test ./...   
      - name: build docker image
        run: docker build -t ghcr.io/deeep8250/movie-ticket-booking-system:latest .
      - name: login to ghcr
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Push docker image to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push  ghcr.io/deeep8250/movie-ticket-booking-system:latest
        

